# Generated by Django 4.0.3 on 2022-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_time', models.DateTimeField(auto_now=True, verbose_name='训练时间')),
                ('task_id', models.IntegerField(verbose_name='对应的任务训练')),
                ('train_type', models.TextField(verbose_name='训练方式')),
                ('train_data', models.CharField(max_length=100, verbose_name='训练数据名称')),
                ('type', models.CharField(max_length=100, verbose_name='训练方式')),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TextField(verbose_name='调度分配')),
                ('result', models.IntegerField(verbose_name='所需时间')),
                ('history_id', models.IntegerField(verbose_name='对应历史记录')),
            ],
        ),
        migrations.CreateModel(
            name='Taskset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('machine', models.IntegerField(verbose_name='处理机数量')),
                ('context', models.TextField(verbose_name='任务内容')),
                ('uploadDate', models.DateTimeField(auto_now=True, verbose_name='上传的时间')),
                ('train_times', models.IntegerField(verbose_name='训练次数')),
                ('recommend', models.CharField(max_length=100, verbose_name='推荐调度算法')),
            ],
        ),
    ]
